import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import Header from "@/components/Header";
import { WalletProvider } from "@/components/WalletProvider";
import SiteBackdrop from "@/components/SiteBackdrop";
import "./globals.css";

const dmMono = DM_Mono({ weight: ["400", "500"], subsets: ["latin"], variable: "--font-dm-mono", display: "swap" });

export const metadata: Metadata = {
  title: { default: "trustset · agent stack", template: "%s · trustset" },
  description: "The off switch in the agent stack. An on-chain kill switch for AI agents on Monad: one transaction from a cold key, and every app that checks refuses the agent in the next block. Built by Silk Nodes.",
  metadataBase: new URL("https://trustset.silknodes.io"),
  applicationName: "trustset",
  authors: [{ name: "Silk Nodes", url: "https://silknodes.io" }],
  /* the card is the brand's social card, regenerated by brand/make.mjs and
     copied to public/og.png. without it, summary_large_image unfurls as an
     empty box everywhere the link is pasted. */
  openGraph: { title: "trustset, the off switch in the agent stack", description: "One transaction from a cold key, and every app that checks refuses the agent in the next block.", url: "https://trustset.silknodes.io", siteName: "trustset · by silk nodes", type: "website", locale: "en_US", images: [{ url: "/og.png", width: 1280, height: 640, alt: "trustset, the off switch in the agent stack. agent 7 REFUSED: paused by its owner, and may come back" }] },
  twitter: { card: "summary_large_image", title: "trustset, the off switch in the agent stack", creator: "@silk_nodes", site: "@silk_nodes", images: ["/og.png"] },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`h-full antialiased ${dmMono.variable}`} suppressHydrationWarning>
      <head>
        {/* theme resolved before first paint, same script as argus */}
        <script dangerouslySetInnerHTML={{ __html: `(function(){try{var t=localStorage.getItem("theme");if(t!=="dark"&&t!=="light"){t=matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"}document.documentElement.dataset.theme=t}catch(e){}})();` }} />
        <link rel="icon" type="image/svg+xml" href="/icon.svg" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
      </head>
      <body className="min-h-full flex flex-col">
        <WalletProvider>
        <SiteBackdrop />
        {/* everything paints above the fixed backdrop, on every page, not only
            the one that used to own it. */}
        <div className="relative" style={{ zIndex: 1 }}>
          <Header />
          {children}
        </div>
        </WalletProvider>
      </body>
    </html>
  );
}
