import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import Header from "@/components/Header";
import { WalletProvider } from "@/components/WalletProvider";
import SiteBackdrop from "@/components/SiteBackdrop";
import "./globals.css";

const dmMono = DM_Mono({ weight: ["400", "500"], subsets: ["latin"], variable: "--font-dm-mono", display: "swap" });

export const metadata: Metadata = {
  title: { default: "trustset · trust stack", template: "%s · trustset" },
  description: "The trust stack for AI agents on Monad. Identity, an off switch, a passkey panic button, guardians, limits, history by timestamp, human proof and refunds, each an immutable contract with no admin. Built by Silk Nodes.",
  metadataBase: new URL("https://trustset.silknodes.io"),
  applicationName: "trustset",
  authors: [{ name: "Silk Nodes", url: "https://silknodes.io" }],
  /* the card is the brand's social card, regenerated by brand/make.mjs and
     copied to public/og.png. without it, summary_large_image unfurls as an
     empty box everywhere the link is pasted. */
  openGraph: { title: "trustset, the trust stack for AI agents", description: "One transaction from its owner, and every app that checks refuses the agent in the next block.", url: "https://trustset.silknodes.io", siteName: "trustset · by silk nodes", type: "website", locale: "en_US", images: [{ url: "/og.png", width: 1280, height: 640, alt: "trustset, the trust stack for AI agents. agent 7 REFUSED: paused by its owner, and may come back" }] },
  twitter: { card: "summary_large_image", title: "trustset, the trust stack for AI agents", creator: "@silk_nodes", site: "@silk_nodes", images: ["/og.png"] },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`h-full antialiased ${dmMono.variable}`} suppressHydrationWarning>
      <head>
        <link rel="icon" type="image/svg+xml" href="/icon.svg" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
      </head>
      <body className="min-h-full flex flex-col">
        {/* the reader's own choice, applied before the body paints.
            this sits at the top of the body rather than in the head because
            react hoists an inline head script below every async chunk tag and
            the whole metadata block, which put it after the stylesheet and
            gave a dark reader a white flash on every reload. here document
            order decides, so nothing below has been painted yet. the system's
            own preference is already handled in css, so this only has to
            carry an explicit choice that disagrees with it. */}
        <script dangerouslySetInnerHTML={{ __html: `(function(){try{var t=localStorage.getItem("theme");if(t==="dark"||t==="light"){document.documentElement.dataset.theme=t}}catch(e){}})();` }} />
        <WalletProvider>
        <SiteBackdrop />
        {/* everything paints above the fixed backdrop, on every page, not only
            the one that used to own it. */}
        <div className="relative" style={{ zIndex: 1 }}>
          <Header />
          {children}
        </div>
        </WalletProvider>
      </body>
    </html>
  );
}
